### PR TITLE
Portuguese (Brazil) translation update

### PR DESCRIPTION
**Pull request by recs182**
I also add some missing keys in the PL and FR json but i'll need appropriated translation.

### CODE REVIEW

**Comment by xnetcat** [comment]
Hi @recs182 i've made pull for Polish translation, u can delete changes in pl.json

**Comment by thomas-cardon** [comment]
There's no need to add missing keys to other languages. The translation modules handles it by giving instead the english language or just the key name if everything's missing. Thanks a lot though! I'm gonna merge it when I've finished fixing a few things.

**Comment by recs182** [comment]
Yeah, I saw it in the updates that you made but I like to keep things constant. I'll control myself next time :P

**Comment by recs182** [comment]
I removed changes for Polish as @kko7 requested!

**Pull request merged**
